trigger:
  branches:
    include:
      - master
  paths:
    include:
      - frontend/**
      - frontend-pipeline.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: MediLink-Secrets
  - name: azureSubscription
    value: 'medilink-azure-connection'
  - name: staticWebAppName
    value: 'medilink-frontend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli@latest
  displayName: 'Install Angular CLI'

- script: npm install
  workingDirectory: frontend/medlink-frontend
  displayName: 'Install dependencies'

- script: npm run build -- --configuration=production
  workingDirectory: frontend/medlink-frontend
  displayName: 'Build Angular'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend/medlink-frontend'
    output_location: 'dist/medlink-frontend'
    azure_static_web_apps_api_token: $(staticWebAppToken)
  displayName: 'Deploy to Azure Static Web App'